openapi: 3.0.0
info:
  version: 0.1.0
  title: Event Schedule API
  description: My API with Swagger
  license:
    name: MIT
servers:
  - url: 'http://localhost:8080/'
paths:
  /api/schedule:
    get:
      tags:
        - /schedule
      summary: schedule list
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
components:
  responses:
    successResponse:
      description: successful request
      content:
        application/json:
          schema:
            type: object
            properties:
              startDate:
                type: string
              endDate:
                type: string
              eventTitle:
                type: string
              typeId:
                type: integer
              bgColor:
                type: string
